In [4]:
import tensorflow as tf
print(tf.__version__)
print(tf.config.list_physical_devices('GPU'))

2.21.0
[]


In [13]:
X = tf.range(10)
dataset = tf.data.Dataset.from_tensor_slices(X)
dataset


<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [18]:
X_nested = {"a": ([1,2,3,], [4,5,6]), "b": [7,8,9]}
dataset = tf.data.Dataset.from_tensor_slices(X_nested)
for i in dataset:
    print(i)

{'a': (<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=4>), 'b': <tf.Tensor: shape=(), dtype=int32, numpy=7>}
{'a': (<tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(), dtype=int32, numpy=5>), 'b': <tf.Tensor: shape=(), dtype=int32, numpy=8>}
{'a': (<tf.Tensor: shape=(), dtype=int32, numpy=3>, <tf.Tensor: shape=(), dtype=int32, numpy=6>), 'b': <tf.Tensor: shape=(), dtype=int32, numpy=9>}


In [27]:
dataset = tf.data.Dataset.from_tensor_slices(tf.range(5))

dataset = dataset.repeat(3).batch(4)
for item in dataset:
    print(item)

tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)
tf.Tensor([4 0 1 2], shape=(4,), dtype=int32)
tf.Tensor([3 4 0 1], shape=(4,), dtype=int32)
tf.Tensor([2 3 4], shape=(3,), dtype=int32)


In [29]:
dataset = dataset.map(lambda x: x*2)
for item in dataset:
    print(item)

tf.Tensor([ 0  4  8 12], shape=(4,), dtype=int32)
tf.Tensor([16  0  4  8], shape=(4,), dtype=int32)
tf.Tensor([12 16  0  4], shape=(4,), dtype=int32)
tf.Tensor([ 8 12 16], shape=(3,), dtype=int32)


In [30]:
for item in dataset.take(2):
    print(item)

tf.Tensor([ 0  4  8 12], shape=(4,), dtype=int32)
tf.Tensor([16  0  4  8], shape=(4,), dtype=int32)


In [52]:
dataset = tf.data.Dataset.range(10).repeat(2)
dataset = dataset.shuffle(buffer_size=2)
for item in dataset.take(10):
    print(item)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
